name: Crear issue con commit

on:
  push:

permissions:
  issues: write
  contents: read

jobs:
  enqueue:
    runs-on: ubuntu-latest
    steps:
      - name: Crear issue directamente con GitHub API
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Deploy pendiente: ${context.sha}`,
              body: `Commit: \`${context.sha}\`\nAutor: ${context.actor}`,
              labels: ['queue']
            });
