name: Encolar commits

on:
  push:

permissions:
  contents: write
  issues: write

jobs:
  enqueue:
    runs-on: ubuntu-latest
    steps:
      - name: Crear issue para commit
        uses: peter-evans/create-issue@v4
        with:
          title: "Deploy pendiente: ${{ github.sha }}"
          body: |
            Commit: `${{ github.sha }}`
            Autor: `${{ github.actor }}`
          labels: queue
